// Code generated by goyacc -o internal/parser/parser.go -v internal/parser/out.output internal/parser/grammar.y. DO NOT EDIT.

//line internal/parser/grammar.y:2
package main

import __yyfmt__ "fmt"

//line internal/parser/grammar.y:2

import (
	"fmt"
	"os"
	"strconv"
)

//line internal/parser/grammar.y:13
type yySymType struct {
	yys int
	str string
	num int
}

const NAMEDEVICE = 57346
const DISPOSITIVO = 57347
const OBSERVATION = 57348
const NUM = 57349
const MSG = 57350
const BOOL = 57351
const OPLOGIC = 57352
const SET = 57353
const IF = 57354
const ELSE = 57355
const THEN = 57356
const AND = 57357
const ALERT = 57358
const SEND = 57359
const LIGAR = 57360
const DESLIGAR = 57361
const VERIFICAR = 57362

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NAMEDEVICE",
	"DISPOSITIVO",
	"OBSERVATION",
	"NUM",
	"MSG",
	"BOOL",
	"OPLOGIC",
	"SET",
	"IF",
	"ELSE",
	"THEN",
	"AND",
	"ALERT",
	"SEND",
	"LIGAR",
	"DESLIGAR",
	"VERIFICAR",
	"':'",
	"'{'",
	"'}'",
	"','",
	"'.'",
	"'='",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line internal/parser/grammar.y:63

type Lexer struct {
	tokens []token
	pos    int
}

type token struct {
	typ int
	val string
}

func (l *Lexer) Lex(lval *yySymType) int {
	if l.pos >= len(l.tokens) {
		return 0
	}
	t := l.tokens[l.pos]
	l.pos++
	switch t.typ {
	case NUM:
		n, _ := strconv.Atoi(t.val)
		lval.num = n

	case NAMEDEVICE, OBSERVATION, MSG, BOOL, OPLOGIC:
		lval.str = t.val
	}
	lval.str = t.val
	return t.typ
}

func (l *Lexer) Error(s string) {
	fmt.Fprintln(os.Stderr, "erro de sintaxe", s)
}

func main() {

	lex := &Lexer{
		tokens: []token{
			{typ: DISPOSITIVO, val: "dispositivo"},
			{typ: int(':'), val: ":"},
			{typ: int('{'), val: "{"},
			{typ: NAMEDEVICE, val: "lampada"},
			{typ: int('}'), val: "}"},

			{typ: LIGAR, val: "ligar"},
			{typ: NAMEDEVICE, val: "lampada"},
			{typ: int('.'), val: "}"},
		},
	}
	yyParse(lex)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 59

var yyAct = [...]int8{
	5, 23, 34, 12, 46, 53, 32, 29, 45, 10,
	11, 41, 42, 52, 21, 15, 16, 17, 18, 27,
	20, 26, 28, 44, 36, 30, 37, 43, 36, 31,
	37, 38, 40, 35, 39, 16, 17, 18, 51, 24,
	47, 22, 4, 54, 48, 50, 49, 33, 25, 2,
	13, 9, 8, 19, 7, 6, 3, 1, 14,
}

var yyPact = [...]int16{
	37, -32768, -2, 37, -1, -32768, -11, -32768, -32768, -32768,
	35, 33, -32768, -32768, 44, 5, -32768, -32768, -32768, -32768,
	-3, -2, -19, 11, 19, -32768, -21, 43, -32768, 17,
	-2, 21, 24, -12, -32768, -32768, -32768, -32768, 14, 8,
	-20, -32768, 34, -2, 33, 41, 32, -10, -32768, -32768,
	-32768, -23, -32768, 39, -32768,
}

var yyPgo = [...]int8{
	0, 58, 57, 49, 0, 56, 55, 54, 52, 51,
	2, 3, 1, 50,
}

var yyR1 = [...]int8{
	0, 2, 3, 3, 5, 5, 4, 4, 6, 6,
	6, 7, 7, 8, 8, 12, 12, 10, 10, 9,
	9, 11, 13, 13, 1, 1, 1,
}

var yyR2 = [...]int8{
	0, 2, 2, 1, 5, 7, 3, 2, 1, 1,
	1, 4, 4, 4, 6, 3, 5, 1, 1, 1,
	1, 2, 6, 8, 1, 1, 1,
}

var yyChk = [...]int16{
	-32768, -2, -3, -5, 5, -4, -6, -7, -8, -9,
	11, 12, -11, -13, -1, 17, 18, 19, 20, -3,
	21, 25, 6, -12, 6, 4, 16, 22, -4, 26,
	14, 10, 27, 4, -10, -11, 7, 9, -4, -10,
	8, 23, 24, 13, 15, 28, 24, 6, -4, -12,
	4, 6, 23, 28, 4,
}

var yyDef = [...]int8{
	0, -2, 0, 3, 0, 1, 0, 8, 9, 10,
	0, 0, 19, 20, 0, 0, 24, 25, 26, 2,
	0, 7, 0, 0, 0, 21, 0, 0, 6, 0,
	0, 0, 0, 0, 11, 12, 17, 18, 13, 15,
	0, 4, 0, 0, 0, 0, 0, 0, 14, 16,
	22, 0, 5, 0, 23,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	27, 28, 3, 3, 24, 3, 25, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 21, 3,
	3, 26, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 22, 3, 23,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/grammar.y:48
		{
			fmt.Printf("%s('%s')\n", yyDollar[1].str, yyDollar[2].str)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:54
		{
			yyVAL.str = "ligar"
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:57
		{
			yyVAL.str = "desligar"
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:60
		{
			yyVAL.str = "verificar"
		}
	}
	goto yystack /* stack new state and value */
}
