// Code generated by goyacc -o internal/parser/parser.go -v internal/parser/out.output internal/parser/grammar.y. DO NOT EDIT.

//line internal/parser/grammar.y:2
package main

import __yyfmt__ "fmt"

//line internal/parser/grammar.y:2

import (
	"fmt"
	"obsactAnalyser/internal/codegen"
	"os"
	"strconv"
	"strings"
)

//line internal/parser/grammar.y:15
type yySymType struct {
	yys int
	str string
	num int
}

const NAMEDEVICE = 57346
const DISPOSITIVO = 57347
const OBSERVATION = 57348
const NUM = 57349
const MSG = 57350
const BOOL = 57351
const OPLOGIC = 57352
const SET = 57353
const IF = 57354
const ELSE = 57355
const ENDIF = 57356
const THEN = 57357
const AND = 57358
const ALERT = 57359
const SEND = 57360
const LIGAR = 57361
const DESLIGAR = 57362
const VERIFICAR = 57363

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NAMEDEVICE",
	"DISPOSITIVO",
	"OBSERVATION",
	"NUM",
	"MSG",
	"BOOL",
	"OPLOGIC",
	"SET",
	"IF",
	"ELSE",
	"ENDIF",
	"THEN",
	"AND",
	"ALERT",
	"SEND",
	"LIGAR",
	"DESLIGAR",
	"VERIFICAR",
	"':'",
	"'{'",
	"'}'",
	"','",
	"'.'",
	"'='",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line internal/parser/grammar.y:113

func indent(s string) string {
	linhas := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, l := range linhas {
		if l != "" {
			linhas[i] = "\t" + l
		}
	}
	return strings.Join(linhas, "\n")
}

type Lexer struct {
	tokens        []token
	pos           int
	GeneratedCode strings.Builder
}

type token struct {
	typ int
	val string
}

func (l *Lexer) Lex(lval *yySymType) int {
	if l.pos >= len(l.tokens) {
		return 0
	}
	t := l.tokens[l.pos]
	l.pos++
	switch t.typ {
	case NUM:
		n, _ := strconv.Atoi(t.val)
		lval.num = n

	case NAMEDEVICE, OBSERVATION, MSG, BOOL, OPLOGIC:
		lval.str = t.val
	}
	return t.typ
}

func (l *Lexer) Error(s string) {
	fmt.Fprintln(os.Stderr, "erro de sintaxe", s)
	if l.pos < len(l.tokens) {
		fmt.Printf("token atual: %+v, posição = %d\n", l.tokens[l.pos], l.pos)
	}
}

func main() {

	lex := &Lexer{
		tokens: []token{
			{typ: DISPOSITIVO, val: "dispositivo"},
			{typ: int(':'), val: ":"}, {typ: int('{'), val: "{"},
			{typ: NAMEDEVICE, val: "celular"}, {typ: int(','), val: ","},
			{typ: OBSERVATION, val: "movimento"}, {typ: int('}'), val: "}"},

			// dispositivo:{higrometro,umidade}
			{typ: DISPOSITIVO, val: "dispositivo"},
			{typ: int(':'), val: ":"}, {typ: int('{'), val: "{"},
			{typ: NAMEDEVICE, val: "higrometro"}, {typ: int(','), val: ","},
			{typ: OBSERVATION, val: "umidade"}, {typ: int('}'), val: "}"},

			// dispositivo:{lampada,potenciaLampada}
			{typ: DISPOSITIVO, val: "dispositivo"},
			{typ: int(':'), val: ":"}, {typ: int('{'), val: "{"},
			{typ: NAMEDEVICE, val: "lampada"}, {typ: int(','), val: ","},
			{typ: OBSERVATION, val: "potenciaLampada"}, {typ: int('}'), val: "}"},

			// dispositivo:{umidificador,potenciaUmidificador}
			{typ: DISPOSITIVO, val: "dispositivo"},
			{typ: int(':'), val: ":"}, {typ: int('{'), val: "{"},
			{typ: NAMEDEVICE, val: "umidificador"}, {typ: int(','), val: ","},
			{typ: OBSERVATION, val: "potenciaUmidificador"}, {typ: int('}'), val: "}"},

			// dispositivo:{Monitor}
			{typ: DISPOSITIVO, val: "dispositivo"},
			{typ: int(':'), val: ":"}, {typ: int('{'), val: "{"},
			{typ: NAMEDEVICE, val: "Monitor"}, {typ: int('}'), val: "}"},

			// set potenciaLampada = 100.   (traduzido da linha "set {lampada,potenciaLampada}=100")
			{typ: SET, val: "set"},
			{typ: OBSERVATION, val: "potenciaLampada"},
			{typ: int('='), val: "="},
			{typ: NUM, val: "100"},
			{typ: int('.'), val: "."},

			// se umidade < 40 entao
			{typ: IF, val: "if"},
			{typ: OBSERVATION, val: "umidade"},
			{typ: OPLOGIC, val: "<"},
			{typ: NUM, val: "40"},
			{typ: THEN, val: "then"},

			// enviar alerta ("Ar seco detectado") Monitor.   (parênteses adicionados p/ casar a regra)
			{typ: SEND, val: "send"},
			{typ: ALERT, val: "alert"},
			{typ: int('('), val: "("},
			{typ: MSG, val: "Ar seco detectado"},
			{typ: int(')'), val: ")"},
			{typ: NAMEDEVICE, val: "Monitor"},
			{typ: int('.'), val: "."},

			// se verificar(umidificador) == 0 entao   (IF aninhado dentro do umidade)
			{typ: IF, val: "if"},
			{typ: VERIFICAR, val: "verificar"},
			{typ: int('('), val: "("},
			{typ: NAMEDEVICE, val: "umidificador"},
			{typ: int(')'), val: ")"},
			{typ: OPLOGIC, val: "=="},
			{typ: NUM, val: "0"},
			{typ: THEN, val: "then"},

			// ligar(umidificador).
			{typ: LIGAR, val: "ligar"},
			{typ: int('('), val: "("},
			{typ: NAMEDEVICE, val: "umidificador"},
			{typ: int(')'), val: ")"},
			{typ: int('.'), val: "."},

			{typ: ENDIF, val: "ENDIF"}, // fecha o IF interno (verificar)

			{typ: int('.'), val: "."},
			// set potenciaUmidificador = 100.
			{typ: SET, val: "set"},
			{typ: OBSERVATION, val: "potenciaUmidificador"},
			{typ: int('='), val: "="},
			{typ: NUM, val: "100"},
			{typ: int('.'), val: "."},

			{typ: ENDIF, val: "ENDIF"}, // fecha o IF externo (umidade)
			{typ: int('.'), val: "."},  // ponto que fecha o CMD do IF externo na sequência

			// se movimento == True entao ligar(lampada) senao desligar(lampada).
			{typ: IF, val: "if"},
			{typ: OBSERVATION, val: "movimento"},
			{typ: OPLOGIC, val: "=="},
			{typ: BOOL, val: "True"},
			{typ: THEN, val: "then"},

			{typ: LIGAR, val: "ligar"},
			{typ: int('('), val: "("},
			{typ: NAMEDEVICE, val: "lampada"},
			{typ: int(')'), val: ")"},
			{typ: int('.'), val: "."}, // ponto fecha o CMDS do then

			{typ: ELSE, val: "else"},

			{typ: DESLIGAR, val: "desligar"},
			{typ: int('('), val: "("},
			{typ: NAMEDEVICE, val: "lampada"},
			{typ: int(')'), val: ")"},
			{typ: int('.'), val: "."}, // ponto fecha o CMDS do else

			{typ: ENDIF, val: "ENDIF"},
			{typ: int('.'), val: "."},
		},
	}
	yyParse(lex)
	final := codegen.RuntimePy + "\n\n" + lex.GeneratedCode.String()
	os.WriteFile("saida.py", []byte(final), 0644)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 71

var yyAct = [...]int8{
	12, 25, 5, 23, 24, 52, 60, 44, 34, 51,
	38, 30, 26, 27, 28, 21, 29, 46, 47, 58,
	32, 20, 10, 11, 33, 31, 16, 17, 18, 15,
	16, 17, 18, 50, 35, 41, 40, 26, 42, 49,
	48, 43, 59, 28, 36, 29, 45, 57, 53, 22,
	4, 26, 54, 61, 55, 16, 17, 18, 56, 39,
	37, 2, 3, 1, 13, 19, 8, 7, 9, 6,
	14,
}

var yyPact = [...]int16{
	45, -32768, 11, 45, -1, -32768, -11, -32768, -32768, -32768,
	43, 7, -32768, -32768, -17, 8, -32768, -32768, -32768, -32768,
	-3, 11, -19, 19, 34, -32768, -32768, -32768, -32768, -32768,
	56, -18, 55, -32768, 36, 11, 7, -22, 38, -7,
	-32768, -32768, 26, 17, -32768, -20, -32768, 42, -32768, 11,
	7, 54, 41, -5, 28, -32768, -32768, -23, -32768, -32768,
	49, -32768,
}

var yyPgo = [...]int8{
	0, 70, 69, 2, 68, 67, 66, 0, 64, 3,
	1, 4, 63, 61, 62,
}

var yyR1 = [...]int8{
	0, 12, 13, 13, 14, 14, 3, 3, 2, 2,
	2, 5, 5, 6, 6, 9, 9, 11, 11, 11,
	10, 10, 4, 4, 7, 8, 8, 1, 1, 1,
}

var yyR2 = [...]int8{
	0, 2, 2, 1, 5, 7, 3, 2, 1, 1,
	1, 4, 4, 5, 7, 3, 5, 1, 1, 1,
	1, 1, 1, 1, 4, 6, 8, 1, 1, 1,
}

var yyChk = [...]int16{
	-32768, -12, -13, -14, 5, -3, -2, -5, -6, -4,
	11, 12, -7, -8, -1, 18, 19, 20, 21, -13,
	22, 26, 6, -9, -11, -10, -7, 6, 7, 9,
	28, 17, 23, -3, 27, 15, 10, 4, 28, 4,
	-10, -7, -3, -11, 29, 8, 24, 25, 14, 13,
	16, 29, 25, 6, -3, -9, 4, 6, 24, 14,
	29, 4,
}

var yyDef = [...]int8{
	0, -2, 0, 3, 0, 1, 0, 8, 9, 10,
	0, 0, 22, 23, 0, 0, 27, 28, 29, 2,
	0, 7, 0, 0, 0, 17, 18, 19, 20, 21,
	0, 0, 0, 6, 0, 0, 0, 0, 0, 0,
	11, 12, 0, 15, 24, 0, 4, 0, 13, 0,
	0, 0, 0, 0, 0, 16, 25, 0, 5, 14,
	0, 26,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	28, 29, 3, 3, 25, 3, 26, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 22, 3,
	3, 27, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 23, 3, 24,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/grammar.y:35
		{
			yylex.(*Lexer).GeneratedCode.WriteString(yyDollar[2].str + "\n")
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/grammar.y:42
		{
			yyVAL.str = yyDollar[1].str + yyDollar[3].str
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/grammar.y:43
		{
			yyVAL.str = yyDollar[1].str
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:45
		{
			yyVAL.str = yyDollar[1].str + "\n"
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:48
		{
			yyVAL.str = yyDollar[1].str + "\n"
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:51
		{
			yyVAL.str = yyDollar[1].str + "\n"
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/grammar.y:55
		{
			yyVAL.str = fmt.Sprintf("%s = %s", yyDollar[2].str, yyDollar[4].str)
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/grammar.y:59
		{
			yyVAL.str = fmt.Sprintf("%s = %s", yyDollar[2].str, yyDollar[4].str)
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/grammar.y:63
		{
			yyVAL.str = fmt.Sprintf("if %s:\n%s", yyDollar[2].str, indent(yyDollar[4].str))
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/grammar.y:68
		{
			yyVAL.str = fmt.Sprintf("if %s:\n%s\nelse:\n%s", yyDollar[2].str, indent(yyDollar[4].str), indent(yyDollar[6].str))
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/grammar.y:72
		{
			yyVAL.str = fmt.Sprintf("%s %s %s", yyDollar[1].str, yyDollar[2].str, yyDollar[3].str)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/grammar.y:76
		{
			yyVAL.str = fmt.Sprintf("%s %s %s and %s", yyDollar[1].str, yyDollar[2].str, yyDollar[3].str, yyDollar[5].str)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:83
		{
			yyVAL.str = strconv.Itoa(yyDollar[1].num)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:86
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/grammar.y:93
		{
			yyVAL.str = fmt.Sprintf("%s('%s')", yyDollar[1].str, yyDollar[3].str)
		}
	case 25:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/grammar.y:96
		{
			yyVAL.str = fmt.Sprintf("alert('%s', '%s')", yyDollar[6].str, yyDollar[4].str)
		}
	case 26:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internal/parser/grammar.y:100
		{
			yyVAL.str = fmt.Sprintf("alert('%s', '%s', '%s')", yyDollar[6].str, yyDollar[4].str, yyDollar[8].str)
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:104
		{
			yyVAL.str = "ligar"
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:107
		{
			yyVAL.str = "desligar"
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:110
		{
			yyVAL.str = "verificar"
		}
	}
	goto yystack /* stack new state and value */
}
