// Code generated by goyacc -o internal/parser/parser.go -v internal/parser/out.output internal/parser/grammar.y. DO NOT EDIT.

//line internal/parser/grammar.y:2
package parser

import __yyfmt__ "fmt"

//line internal/parser/grammar.y:2

import (
	"fmt"
	"os"
	"strconv"
	"strings"
)

//line internal/parser/grammar.y:14
type yySymType struct {
	yys int
	str string
	num int
}

const DISPOSITIVO = 57346
const NUM = 57347
const MSG = 57348
const PARA = 57349
const TODOS = 57350
const IDENT = 57351
const BOOL = 57352
const OPLOGIC = 57353
const SET = 57354
const IF = 57355
const ELSE = 57356
const ENDIF = 57357
const THEN = 57358
const AND = 57359
const ALERT = 57360
const SEND = 57361
const LIGAR = 57362
const DESLIGAR = 57363
const VERIFICAR = 57364

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"DISPOSITIVO",
	"NUM",
	"MSG",
	"PARA",
	"TODOS",
	"IDENT",
	"BOOL",
	"OPLOGIC",
	"SET",
	"IF",
	"ELSE",
	"ENDIF",
	"THEN",
	"AND",
	"ALERT",
	"SEND",
	"LIGAR",
	"DESLIGAR",
	"VERIFICAR",
	"':'",
	"'{'",
	"'}'",
	"','",
	"'.'",
	"'='",
	"'('",
	"')'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line internal/parser/grammar.y:142

func indent(s string) string {
	linhas := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, l := range linhas {
		if l != "" {
			linhas[i] = "\t" + l
		}
	}
	return strings.Join(linhas, "\n")
}

type Lexer struct {
	Tokens        chan token
	pos           int
	GeneratedCode strings.Builder
}

type token struct {
	typ int
	val string
}

func (l *Lexer) Lex(lval *yySymType) int {
	t, ok := <-l.Tokens
	if !ok {
		return 0
	}
	fmt.Printf("TOKEN %-12s val=%q\n", t.typ, t.val)
	switch t.typ {
	case NUM:
		n, _ := strconv.Atoi(t.val)
		lval.num = n
	case IDENT, MSG, BOOL, OPLOGIC:
		lval.str = t.val
	}
	return t.typ
}

func (l *Lexer) Error(s string) {
	fmt.Fprintln(os.Stderr, "erro de sintaxe", s)
}
func Parse(lex yyLexer) int {
	return yyParse(lex)
}

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 82

var yyAct = [...]int8{
	66, 12, 25, 5, 23, 24, 52, 62, 44, 34,
	51, 38, 30, 26, 28, 46, 47, 69, 27, 29,
	21, 59, 32, 70, 63, 33, 20, 50, 28, 16,
	17, 18, 31, 29, 49, 48, 41, 40, 26, 42,
	10, 11, 43, 16, 17, 18, 35, 15, 16, 17,
	18, 60, 26, 54, 36, 55, 64, 57, 65, 56,
	67, 58, 53, 39, 37, 22, 68, 61, 45, 4,
	71, 72, 2, 1, 3, 13, 19, 8, 7, 9,
	6, 14,
}

var yyPact = [...]int16{
	65, -32768, 28, 65, 3, -32768, -7, -32768, -32768, -32768,
	56, 9, -32768, -32768, -17, 14, -32768, -32768, -32768, -32768,
	-2, 28, -19, 30, 43, -32768, -32768, -32768, -32768, -32768,
	55, -18, 54, -32768, 23, 28, 9, -22, 62, -10,
	-32768, -32768, 20, 10, -32768, -20, -32768, 53, -32768, 28,
	9, 50, 52, -4, 36, -32768, -32768, 59, -23, -32768,
	-32768, 1, 49, 51, 58, -32768, -32768, -9, 0, 51,
	51, -32768, -32768,
}

var yyPgo = [...]int8{
	0, 81, 80, 3, 79, 78, 77, 1, 75, 4,
	2, 5, 74, 72, 0, 73,
}

var yyR1 = [...]int8{
	0, 15, 12, 12, 13, 13, 3, 3, 2, 2,
	2, 5, 5, 6, 6, 9, 9, 11, 11, 11,
	10, 10, 4, 4, 7, 8, 8, 8, 14, 14,
	8, 1, 1, 1,
}

var yyR2 = [...]int8{
	0, 2, 5, 7, 2, 1, 3, 2, 1, 1,
	1, 4, 4, 5, 7, 3, 5, 1, 1, 1,
	1, 1, 1, 1, 4, 6, 9, 11, 3, 1,
	8, 1, 1, 1,
}

var yyChk = [...]int16{
	-32768, -15, -13, -12, 4, -3, -2, -5, -6, -4,
	12, 13, -7, -8, -1, 19, 20, 21, 22, -13,
	23, 27, 9, -9, -11, -10, -7, 9, 5, 10,
	29, 18, 24, -3, 28, 16, 11, 9, 29, 9,
	-10, -7, -3, -11, 30, 6, 25, 26, 15, 14,
	17, 30, 26, 9, -3, -9, 9, 7, 9, 25,
	15, 8, 30, 23, 7, 9, -14, 9, 8, 26,
	23, -14, -14,
}

var yyDef = [...]int8{
	0, -2, 0, 5, 0, 1, 0, 8, 9, 10,
	0, 0, 22, 23, 0, 0, 31, 32, 33, 4,
	0, 7, 0, 0, 0, 17, 18, 19, 20, 21,
	0, 0, 0, 6, 0, 0, 0, 0, 0, 0,
	11, 12, 0, 15, 24, 0, 2, 0, 13, 0,
	0, 0, 0, 0, 0, 16, 25, 0, 0, 3,
	14, 0, 0, 0, 0, 30, 26, 29, 0, 0,
	0, 28, 27,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	29, 30, 3, 3, 26, 3, 27, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 23, 3,
	3, 28, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 24, 3, 25,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -32768

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/grammar.y:35
		{
			yylex.(*Lexer).GeneratedCode.WriteString(yyDollar[1].str + yyDollar[2].str + "\n")
		}
	case 2:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/grammar.y:39
		{
			yyVAL.str = ""
		}
	case 3:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/grammar.y:42
		{
			yyVAL.str = fmt.Sprintf("%s = 0\n", yyDollar[6].str)
		}
	case 4:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/grammar.y:48
		{
			yyVAL.str = yyDollar[1].str + yyDollar[2].str
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:49
		{
			yyVAL.str = yyDollar[1].str
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/grammar.y:52
		{
			yyVAL.str = yyDollar[1].str + yyDollar[3].str
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line internal/parser/grammar.y:53
		{
			yyVAL.str = yyDollar[1].str
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:55
		{
			yyVAL.str = yyDollar[1].str + "\n"
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:58
		{
			yyVAL.str = yyDollar[1].str + "\n"
		}
	case 10:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:61
		{
			yyVAL.str = yyDollar[1].str + "\n"
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/grammar.y:65
		{
			yyVAL.str = fmt.Sprintf("%s = %s", yyDollar[2].str, yyDollar[4].str)
		}
	case 12:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/grammar.y:69
		{
			yyVAL.str = fmt.Sprintf("%s = %s", yyDollar[2].str, yyDollar[4].str)
		}
	case 13:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/grammar.y:73
		{
			yyVAL.str = fmt.Sprintf("if %s:\n%s", yyDollar[2].str, indent(yyDollar[4].str))
		}
	case 14:
		yyDollar = yyS[yypt-7 : yypt+1]
//line internal/parser/grammar.y:78
		{
			yyVAL.str = fmt.Sprintf("if %s:\n%s\nelse:\n%s", yyDollar[2].str, indent(yyDollar[4].str), indent(yyDollar[6].str))
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/grammar.y:82
		{
			yyVAL.str = fmt.Sprintf("%s %s %s", yyDollar[1].str, yyDollar[2].str, yyDollar[3].str)
		}
	case 16:
		yyDollar = yyS[yypt-5 : yypt+1]
//line internal/parser/grammar.y:86
		{
			yyVAL.str = fmt.Sprintf("%s %s %s and %s", yyDollar[1].str, yyDollar[2].str, yyDollar[3].str, yyDollar[5].str)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:93
		{
			yyVAL.str = strconv.Itoa(yyDollar[1].num)
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:96
		{
			yyVAL.str = yyDollar[1].str
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line internal/parser/grammar.y:103
		{
			yyVAL.str = fmt.Sprintf("%s('%s')", yyDollar[1].str, yyDollar[3].str)
		}
	case 25:
		yyDollar = yyS[yypt-6 : yypt+1]
//line internal/parser/grammar.y:106
		{
			yyVAL.str = fmt.Sprintf("alert('%s', '%s')", yyDollar[6].str, yyDollar[4].str)
		}
	case 26:
		yyDollar = yyS[yypt-9 : yypt+1]
//line internal/parser/grammar.y:109
		{
			lista := strings.Split(yyDollar[9].str, ",")
			var sb strings.Builder
			for _, val := range lista {
				sb.WriteString(fmt.Sprintf("alert('%s', '%s')\n", val, yyDollar[4].str))
			}
			yyVAL.str = sb.String()
		}
	case 27:
		yyDollar = yyS[yypt-11 : yypt+1]
//line internal/parser/grammar.y:117
		{
			lista := strings.Split(yyDollar[11].str, ",")
			var sb strings.Builder
			for _, dev := range lista {
				sb.WriteString(fmt.Sprintf("alert('%s', '%s', '%s')\n", dev, yyDollar[4].str, yyDollar[6].str))
			}
			yyVAL.str = sb.String()
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line internal/parser/grammar.y:126
		{
			yyVAL.str = yyDollar[1].str + "," + yyDollar[3].str
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:127
		{
			yyVAL.str = yyDollar[1].str
		}
	case 30:
		yyDollar = yyS[yypt-8 : yypt+1]
//line internal/parser/grammar.y:129
		{
			yyVAL.str = fmt.Sprintf("alert('%s', '%s', '%s')", yyDollar[6].str, yyDollar[4].str, yyDollar[8].str)
		}
	case 31:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:133
		{
			yyVAL.str = "ligar"
		}
	case 32:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:136
		{
			yyVAL.str = "desligar"
		}
	case 33:
		yyDollar = yyS[yypt-1 : yypt+1]
//line internal/parser/grammar.y:139
		{
			yyVAL.str = "verificar"
		}
	}
	goto yystack /* stack new state and value */
}
